import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from "./components/navigation";
import store from "@/app/store/store"
import {Provider} from "react-redux"
import Roles from "@/app/roles/page"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Titans-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Navigation />
        <div className="w-full flex justify-center">
          {children}
        </div>
    </>
  //   <Provider store={store}>
  //     <Roles/>
  //   </Provider>
  )
}

