import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from "@/src/store/provider"
import Navbar from "@/src/components/navbar"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Titans-App',
  description: 'Generated by create next app',
}

export default function RootLayout({
   children,
 }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body suppressHydrationWarning={true}>
    <Navbar />
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  )
}

